stages:
  - verify
  - build

flake8:
  image: python:3
  stage: verify
  before_script:
    - pip install flake8
  script:
    - flake8 .

build_container:
  image: rotterdam.selfnet.de/noc/container-build/container-build:latest
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah bud -t $CI_REGISTRY_IMAGE/radosgw-exporter:latest .
    - if [ "$CI_COMMIT_REF_NAME" == "main" ]; then buildah push $CI_REGISTRY_IMAGE/radosgw-exporter:latest; fi

release_build:
  image: rotterdam.selfnet.de/noc/container-build/container-build:latest
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah bud -t $CI_REGISTRY_IMAGE/radosgw-exporter:$CI_COMMIT_REF_NAME .
    - buildah push $CI_REGISTRY_IMAGE/radosgw-exporter:$CI_COMMIT_REF_NAME
  only:
    - tags
